
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AkshayKumarPhatale/cloud-configs.git
      name: config-server

        

management:
  endpoint:
    health:
      show-details: always
